# Generated by Django 5.1.3 on 2024-12-10 16:13

import datetime
import django.db.models.deletion
import django.utils.timezone
import school_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=10)),
                ('so_hoc_sinh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=200, unique=True)),
                ('ten_mon', models.CharField(max_length=200, unique=True)),
                ('diem_chuan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=200, unique=True)),
                ('tuoi_toi_da', models.IntegerField()),
                ('tuoi_toi_thieu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('vai_tro', models.CharField(choices=[('1', 'Quản trị viên'), ('2', 'Giáo viên'), ('3', 'Học sinh')], default='1', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('ho_ten', models.CharField(default='', max_length=200)),
                ('ngay_sinh', models.DateField(default=datetime.date.today)),
                ('gioi_tinh', models.CharField(choices=[('1', 'Nam'), ('0', 'Nữ')], default='1', max_length=1)),
                ('so_dien_thoai', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('dia_chi', models.TextField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', school_app.models.NguoiDungManager()),
            ],
        ),
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lop_hoc', models.ManyToManyField(blank=True, to='school_app.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='KetQua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoc_ki', models.CharField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2')], max_length=200)),
                ('diem_15phut', models.FloatField(blank=True, null=True)),
                ('diem_1tiet', models.FloatField(blank=True, null=True)),
                ('diem_final', models.FloatField(blank=True, null=True)),
                ('hoc_sinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.hocsinh')),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mon_day', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monhoc',
            name='nam_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.tuoi'),
        ),
        migrations.AddField(
            model_name='lophoc',
            name='nam_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.tuoi'),
        ),
        migrations.AddConstraint(
            model_name='nguoidung',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_user'),
        ),
    ]
