# Generated by Django 5.1.3 on 2024-12-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tuoi',
            new_name='NamHoc',
        ),
        migrations.RenameModel(
            old_name='NhanVien',
            new_name='QuanTriVien',
        ),
    ]
