# Generated by Django 5.1.3 on 2024-12-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_rename_tuoi_namhoc_rename_nhanvien_quantrivien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='so_hoc_sinh',
            field=models.IntegerField(null=True),
        ),
    ]
