# Generated by Django 5.1.3 on 2024-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_lophoc_so_hoc_sinh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ketqua',
            old_name='diem_final',
            new_name='diem_ck',
        ),
        migrations.AddField(
            model_name='ketqua',
            name='diem_gk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
