# Generated by Django 5.1.3 on 2024-12-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_rename_diem_final_ketqua_diem_ck_ketqua_diem_gk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monhoc',
            name='nam_hoc',
        ),
        migrations.AddField(
            model_name='giaovien',
            name='lop_day',
            field=models.ManyToManyField(blank=True, to='school_app.lophoc'),
        ),
        migrations.AddField(
            model_name='ketqua',
            name='nam_hoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_app.namhoc'),
            preserve_default=False,
        ),
    ]
