# Generated by Django 5.1.3 on 2024-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_remove_monhoc_nam_hoc_giaovien_lop_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketqua',
            name='diem_tong',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
