# Generated by Django 5.1.3 on 2024-12-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_ketquamonhoc_ketquanamhoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='giao_vien_chu_nhiem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.giaovien'),
        ),
    ]
