# Generated by Django 5.1.3 on 2024-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_lophoc_giao_vien_chu_nhiem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketquanamhoc',
            name='hanh_kiem',
            field=models.CharField(blank=True, choices=[('Tot', 'Tốt'), ('Kha', 'Khá'), ('TrungBinh', 'Trung bình'), ('Yeu', 'Yếu')], max_length=10, null=True),
        ),
    ]
